language: python
python:
  - "2.7"
  - "3.2"
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - "python setup.py develop"
  - "pip install -q -U pip setuptools tox coveralls"
# command to run tests
script: tox
